services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: notesdb
      MYSQL_USER: notesuser
      MYSQL_PASSWORD: notespass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"

  web:
    image: shivamnegi07/notes-app:latest
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: notesdb
      DB_USER: notesuser
      DB_PASSWORD: notespass
      DB_HOST: db
      DB_PORT: 3306
